name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions: {}

jobs:
  ci:
    timeout-minutes: 15
    permissions:
      contents: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium


      - name: Check Linux rolldown
        if: matrix.os == 'ubuntu-latest'
        run: |
          node -e "console.log(require('./node_modules/@voidzero-dev/vite-plus/dist/rolldown/shared/rolldown-binding.linux-x64-gnu.node'))"
      - name: Check ready
        run: |
          pnpm ready
          # run again to check cache hits
          pnpm ready

      - name: Check build artifacts
        run: |
          if [ -d "apps/dashboard/dist" ]; then
            echo "✅ Build artifacts created successfully"
            ls -la apps/dashboard/dist/
          else
            echo "❌ Build artifacts not found"
            exit 1
          fi

  global:
    timeout-minutes: 15
    permissions:
      contents: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@voidzero-dev'
          package-manager-cache: false

      - run: npm install -g @voidzero-dev/global@latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: vite --version
      - run: vite fmt -c .oxfmtrc.jsonc --check

      - run: vite lint -c .oxlintrc.json
